// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// intPower
int intPower(int a, int b);
RcppExport SEXP _MultiOutbreaks_intPower(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(intPower(a, b));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp_cpp2
double logSumExp_cpp2(arma::vec x);
RcppExport SEXP _MultiOutbreaks_logSumExp_cpp2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp_cpp2(x));
    return rcpp_result_gen;
END_RCPP
}
// logVecMatMult2
arma::vec logVecMatMult2(arma::vec logV, arma::mat logM);
RcppExport SEXP _MultiOutbreaks_logVecMatMult2(SEXP logVSEXP, SEXP logMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type logV(logVSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type logM(logMSEXP);
    rcpp_result_gen = Rcpp::wrap(logVecMatMult2(logV, logM));
    return rcpp_result_gen;
END_RCPP
}
// stationarydistArma_cpp
arma::vec stationarydistArma_cpp(arma::mat Gamma);
RcppExport SEXP _MultiOutbreaks_stationarydistArma_cpp(SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(stationarydistArma_cpp(Gamma));
    return rcpp_result_gen;
END_RCPP
}
// randomwalk2_cpp
double randomwalk2_cpp(arma::vec componentR, double PrecisionR);
RcppExport SEXP _MultiOutbreaks_randomwalk2_cpp(SEXP componentRSEXP, SEXP PrecisionRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type componentR(componentRSEXP);
    Rcpp::traits::input_parameter< double >::type PrecisionR(PrecisionRSEXP);
    rcpp_result_gen = Rcpp::wrap(randomwalk2_cpp(componentR, PrecisionR));
    return rcpp_result_gen;
END_RCPP
}
// seasonalComp2_cpp
double seasonalComp2_cpp(const arma::vec& x, double y, const arma::mat& z);
RcppExport SEXP _MultiOutbreaks_seasonalComp2_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(seasonalComp2_cpp(x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// logIGMRF1_cpp
double logIGMRF1_cpp(const arma::vec& x, double y, const arma::mat& z, int rankdef);
RcppExport SEXP _MultiOutbreaks_logIGMRF1_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP rankdefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type rankdef(rankdefSEXP);
    rcpp_result_gen = Rcpp::wrap(logIGMRF1_cpp(x, y, z, rankdef));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_arma_cpp
arma::mat JointTransitionMatrix_arma_cpp(arma::mat gamma, int K);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_arma_cpp(SEXP gammaSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_arma_cpp(gamma, K));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_per_strain_cpp2
arma::mat JointTransitionMatrix_per_strain_cpp2(List gamma_list, int K);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_per_strain_cpp2(SEXP gamma_listSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_per_strain_cpp2(gamma_list, K));
    return rcpp_result_gen;
END_RCPP
}
// one_factor_copula_cdf_rcpp
double one_factor_copula_cdf_rcpp(const arma::vec& u, const arma::vec& Lambdas, const arma::vec& gh_x, const arma::vec& gh_w);
RcppExport SEXP _MultiOutbreaks_one_factor_copula_cdf_rcpp(SEXP uSEXP, SEXP LambdasSEXP, SEXP gh_xSEXP, SEXP gh_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Lambdas(LambdasSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gh_x(gh_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gh_w(gh_wSEXP);
    rcpp_result_gen = Rcpp::wrap(one_factor_copula_cdf_rcpp(u, Lambdas, gh_x, gh_w));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_1FactorGaussiancopula_cpp
arma::mat JointTransitionMatrix_1FactorGaussiancopula_cpp(const arma::mat& gamma, int K, const arma::vec& Lambdas, const arma::vec& gh_x, const arma::vec& gh_w);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_1FactorGaussiancopula_cpp(SEXP gammaSEXP, SEXP KSEXP, SEXP LambdasSEXP, SEXP gh_xSEXP, SEXP gh_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Lambdas(LambdasSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gh_x(gh_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gh_w(gh_wSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_1FactorGaussiancopula_cpp(gamma, K, Lambdas, gh_x, gh_w));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_1FactorGaussiancopula_per_strain_cpp
arma::mat JointTransitionMatrix_1FactorGaussiancopula_per_strain_cpp(List gamma_list, int K, const arma::vec& Lambdas, const arma::vec& gh_x, const arma::vec& gh_w);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_1FactorGaussiancopula_per_strain_cpp(SEXP gamma_listSEXP, SEXP KSEXP, SEXP LambdasSEXP, SEXP gh_xSEXP, SEXP gh_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Lambdas(LambdasSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gh_x(gh_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gh_w(gh_wSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_1FactorGaussiancopula_per_strain_cpp(gamma_list, K, Lambdas, gh_x, gh_w));
    return rcpp_result_gen;
END_RCPP
}
// frank_cdf_cpp2
double frank_cdf_cpp2(const arma::vec& u, double theta);
RcppExport SEXP _MultiOutbreaks_frank_cdf_cpp2(SEXP uSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(frank_cdf_cpp2(u, theta));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_Frankcopula_cpp
arma::mat JointTransitionMatrix_Frankcopula_cpp(const arma::mat& gamma, int K, double copParam);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_Frankcopula_cpp(SEXP gammaSEXP, SEXP KSEXP, SEXP copParamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type copParam(copParamSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_Frankcopula_cpp(gamma, K, copParam));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_Frankcopula_perstrain_cpp
arma::mat JointTransitionMatrix_Frankcopula_perstrain_cpp(List gamma_list, int K, double copParam);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_Frankcopula_perstrain_cpp(SEXP gamma_listSEXP, SEXP KSEXP, SEXP copParamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type copParam(copParamSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_Frankcopula_perstrain_cpp(gamma_list, K, copParam));
    return rcpp_result_gen;
END_RCPP
}
// makematrix_arma_cpp2
arma::mat makematrix_arma_cpp2(double g12, double g21);
RcppExport SEXP _MultiOutbreaks_makematrix_arma_cpp2(SEXP g12SEXP, SEXP g21SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type g12(g12SEXP);
    Rcpp::traits::input_parameter< double >::type g21(g21SEXP);
    rcpp_result_gen = Rcpp::wrap(makematrix_arma_cpp2(g12, g21));
    return rcpp_result_gen;
END_RCPP
}
// BuildGamma_list_cpp
Rcpp::List BuildGamma_list_cpp(const arma::vec& Gs);
RcppExport SEXP _MultiOutbreaks_BuildGamma_list_cpp(SEXP GsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Gs(GsSEXP);
    rcpp_result_gen = Rcpp::wrap(BuildGamma_list_cpp(Gs));
    return rcpp_result_gen;
END_RCPP
}
// build_corr_from_params_cpp
arma::mat build_corr_from_params_cpp(int d, const arma::vec& params);
RcppExport SEXP _MultiOutbreaks_build_corr_from_params_cpp(SEXP dSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_corr_from_params_cpp(d, params));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_copula_cdf_cpp
double gaussian_copula_cdf_cpp(const arma::vec& u, const arma::mat& corrMat);
RcppExport SEXP _MultiOutbreaks_gaussian_copula_cdf_cpp(SEXP uSEXP, SEXP corrMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type corrMat(corrMatSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_copula_cdf_cpp(u, corrMat));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_Gaussiancopula_cpp
arma::mat JointTransitionMatrix_Gaussiancopula_cpp(const arma::mat& gamma, int K, const arma::vec& copParams);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_Gaussiancopula_cpp(SEXP gammaSEXP, SEXP KSEXP, SEXP copParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type copParams(copParamsSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_Gaussiancopula_cpp(gamma, K, copParams));
    return rcpp_result_gen;
END_RCPP
}
// JointTransitionMatrix_Gaussiancopula_perstrain_cpp
arma::mat JointTransitionMatrix_Gaussiancopula_perstrain_cpp(List gamma_list, int K, const arma::vec& copParams);
RcppExport SEXP _MultiOutbreaks_JointTransitionMatrix_Gaussiancopula_perstrain_cpp(SEXP gamma_listSEXP, SEXP KSEXP, SEXP copParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type copParams(copParamsSEXP);
    rcpp_result_gen = Rcpp::wrap(JointTransitionMatrix_Gaussiancopula_perstrain_cpp(gamma_list, K, copParams));
    return rcpp_result_gen;
END_RCPP
}
// replace_naMat_with_zero
arma::mat replace_naMat_with_zero(arma::mat X);
RcppExport SEXP _MultiOutbreaks_replace_naMat_with_zero(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(replace_naMat_with_zero(X));
    return rcpp_result_gen;
END_RCPP
}
// replace_naVec_with_zero
arma::vec replace_naVec_with_zero(arma::vec X);
RcppExport SEXP _MultiOutbreaks_replace_naVec_with_zero(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(replace_naVec_with_zero(X));
    return rcpp_result_gen;
END_RCPP
}
// SMOOTHINGgradmultstrainLoglikelihood_cpp
List SMOOTHINGgradmultstrainLoglikelihood_cpp(arma::cube y, arma::mat e_it, int nstrain, arma::vec r, arma::vec s, arma::vec u, arma::mat jointTPM, arma::vec B, arma::mat Bits, arma::vec a_k, int Model, arma::mat Q_r, arma::mat Q_s, arma::mat Q_u, int gradients);
RcppExport SEXP _MultiOutbreaks_SMOOTHINGgradmultstrainLoglikelihood_cpp(SEXP ySEXP, SEXP e_itSEXP, SEXP nstrainSEXP, SEXP rSEXP, SEXP sSEXP, SEXP uSEXP, SEXP jointTPMSEXP, SEXP BSEXP, SEXP BitsSEXP, SEXP a_kSEXP, SEXP ModelSEXP, SEXP Q_rSEXP, SEXP Q_sSEXP, SEXP Q_uSEXP, SEXP gradientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e_it(e_itSEXP);
    Rcpp::traits::input_parameter< int >::type nstrain(nstrainSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type jointTPM(jointTPMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bits(BitsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_k(a_kSEXP);
    Rcpp::traits::input_parameter< int >::type Model(ModelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_r(Q_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_s(Q_sSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_u(Q_uSEXP);
    Rcpp::traits::input_parameter< int >::type gradients(gradientsSEXP);
    rcpp_result_gen = Rcpp::wrap(SMOOTHINGgradmultstrainLoglikelihood_cpp(y, e_it, nstrain, r, s, u, jointTPM, B, Bits, a_k, Model, Q_r, Q_s, Q_u, gradients));
    return rcpp_result_gen;
END_RCPP
}
// FFBSgradmultstrainLoglikelihood_cpp
List FFBSgradmultstrainLoglikelihood_cpp(arma::cube y, arma::mat e_it, int nstrain, arma::vec r, arma::vec s, arma::vec u, arma::mat jointTPM, arma::vec B, arma::mat Bits, arma::vec a_k, int Model, arma::mat Q_r, arma::mat Q_s, arma::mat Q_u, int gradients);
RcppExport SEXP _MultiOutbreaks_FFBSgradmultstrainLoglikelihood_cpp(SEXP ySEXP, SEXP e_itSEXP, SEXP nstrainSEXP, SEXP rSEXP, SEXP sSEXP, SEXP uSEXP, SEXP jointTPMSEXP, SEXP BSEXP, SEXP BitsSEXP, SEXP a_kSEXP, SEXP ModelSEXP, SEXP Q_rSEXP, SEXP Q_sSEXP, SEXP Q_uSEXP, SEXP gradientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e_it(e_itSEXP);
    Rcpp::traits::input_parameter< int >::type nstrain(nstrainSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type jointTPM(jointTPMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bits(BitsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_k(a_kSEXP);
    Rcpp::traits::input_parameter< int >::type Model(ModelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_r(Q_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_s(Q_sSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_u(Q_uSEXP);
    Rcpp::traits::input_parameter< int >::type gradients(gradientsSEXP);
    rcpp_result_gen = Rcpp::wrap(FFBSgradmultstrainLoglikelihood_cpp(y, e_it, nstrain, r, s, u, jointTPM, B, Bits, a_k, Model, Q_r, Q_s, Q_u, gradients));
    return rcpp_result_gen;
END_RCPP
}
// PostOutbreakProbs_cpp
arma::cube PostOutbreakProbs_cpp(arma::cube y, arma::mat e_it, int nstrain, arma::vec r, arma::vec s, arma::vec u, arma::mat jointTPM, arma::vec B, arma::mat Bits, arma::vec a_k);
RcppExport SEXP _MultiOutbreaks_PostOutbreakProbs_cpp(SEXP ySEXP, SEXP e_itSEXP, SEXP nstrainSEXP, SEXP rSEXP, SEXP sSEXP, SEXP uSEXP, SEXP jointTPMSEXP, SEXP BSEXP, SEXP BitsSEXP, SEXP a_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e_it(e_itSEXP);
    Rcpp::traits::input_parameter< int >::type nstrain(nstrainSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type jointTPM(jointTPMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bits(BitsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_k(a_kSEXP);
    rcpp_result_gen = Rcpp::wrap(PostOutbreakProbs_cpp(y, e_it, nstrain, r, s, u, jointTPM, B, Bits, a_k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiOutbreaks_intPower", (DL_FUNC) &_MultiOutbreaks_intPower, 2},
    {"_MultiOutbreaks_logSumExp_cpp2", (DL_FUNC) &_MultiOutbreaks_logSumExp_cpp2, 1},
    {"_MultiOutbreaks_logVecMatMult2", (DL_FUNC) &_MultiOutbreaks_logVecMatMult2, 2},
    {"_MultiOutbreaks_stationarydistArma_cpp", (DL_FUNC) &_MultiOutbreaks_stationarydistArma_cpp, 1},
    {"_MultiOutbreaks_randomwalk2_cpp", (DL_FUNC) &_MultiOutbreaks_randomwalk2_cpp, 2},
    {"_MultiOutbreaks_seasonalComp2_cpp", (DL_FUNC) &_MultiOutbreaks_seasonalComp2_cpp, 3},
    {"_MultiOutbreaks_logIGMRF1_cpp", (DL_FUNC) &_MultiOutbreaks_logIGMRF1_cpp, 4},
    {"_MultiOutbreaks_JointTransitionMatrix_arma_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_arma_cpp, 2},
    {"_MultiOutbreaks_JointTransitionMatrix_per_strain_cpp2", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_per_strain_cpp2, 2},
    {"_MultiOutbreaks_one_factor_copula_cdf_rcpp", (DL_FUNC) &_MultiOutbreaks_one_factor_copula_cdf_rcpp, 4},
    {"_MultiOutbreaks_JointTransitionMatrix_1FactorGaussiancopula_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_1FactorGaussiancopula_cpp, 5},
    {"_MultiOutbreaks_JointTransitionMatrix_1FactorGaussiancopula_per_strain_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_1FactorGaussiancopula_per_strain_cpp, 5},
    {"_MultiOutbreaks_frank_cdf_cpp2", (DL_FUNC) &_MultiOutbreaks_frank_cdf_cpp2, 2},
    {"_MultiOutbreaks_JointTransitionMatrix_Frankcopula_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_Frankcopula_cpp, 3},
    {"_MultiOutbreaks_JointTransitionMatrix_Frankcopula_perstrain_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_Frankcopula_perstrain_cpp, 3},
    {"_MultiOutbreaks_makematrix_arma_cpp2", (DL_FUNC) &_MultiOutbreaks_makematrix_arma_cpp2, 2},
    {"_MultiOutbreaks_BuildGamma_list_cpp", (DL_FUNC) &_MultiOutbreaks_BuildGamma_list_cpp, 1},
    {"_MultiOutbreaks_build_corr_from_params_cpp", (DL_FUNC) &_MultiOutbreaks_build_corr_from_params_cpp, 2},
    {"_MultiOutbreaks_gaussian_copula_cdf_cpp", (DL_FUNC) &_MultiOutbreaks_gaussian_copula_cdf_cpp, 2},
    {"_MultiOutbreaks_JointTransitionMatrix_Gaussiancopula_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_Gaussiancopula_cpp, 3},
    {"_MultiOutbreaks_JointTransitionMatrix_Gaussiancopula_perstrain_cpp", (DL_FUNC) &_MultiOutbreaks_JointTransitionMatrix_Gaussiancopula_perstrain_cpp, 3},
    {"_MultiOutbreaks_replace_naMat_with_zero", (DL_FUNC) &_MultiOutbreaks_replace_naMat_with_zero, 1},
    {"_MultiOutbreaks_replace_naVec_with_zero", (DL_FUNC) &_MultiOutbreaks_replace_naVec_with_zero, 1},
    {"_MultiOutbreaks_SMOOTHINGgradmultstrainLoglikelihood_cpp", (DL_FUNC) &_MultiOutbreaks_SMOOTHINGgradmultstrainLoglikelihood_cpp, 15},
    {"_MultiOutbreaks_FFBSgradmultstrainLoglikelihood_cpp", (DL_FUNC) &_MultiOutbreaks_FFBSgradmultstrainLoglikelihood_cpp, 15},
    {"_MultiOutbreaks_PostOutbreakProbs_cpp", (DL_FUNC) &_MultiOutbreaks_PostOutbreakProbs_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiOutbreaks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
